/** Stable mini-program routes shared by hubs, navigation and package contracts. */
export const ROUTES = Object.freeze({
  HOME: "/pages/index/index",
  MENU: "/pages/menu/index",
  ORDERS: "/pages/my-orders/index",
  GAMES: "/pages/games/index",
  COUPLE: "/pages/couple/index",
  GOMOKU: "/pages/games/gomoku/index",
  FLIGHT: "/pages/games/flight/index",
  LANDLORD: "/pages/games/landlord/index",
  ANIMAL: "/pages/games/animal/index",
  CHESS: "/pages/games/chess/index",
  GAME_RANKING: "/pages/games/ranking/index",
  GAME_AI: "/pages/games/ai/index",
  DICE: "/pages/dice/index",
  DICE_ONLINE: "/pages/dice-online/index",
  WHEEL: "/pages/wheel/index",
  COUPLE_SCORE: "/pages/couple/score",
  COUPLE_RECORDS: "/pages/couple/records",
  COUPLE_ACHIEVEMENTS: "/pages/couple/achievements",
  COUPLE_GAME_RECORDS: "/pages/couple/game-records",
  COUPLE_TASKS: "/pages/couple/tasks",
  COUPLE_TIMELINE: "/pages/couple/timeline",
  NOTIFICATIONS: "/pages/notifications/index",
  PROFILE: "/pages/profile/index",
  ADMIN_LOGIN: "/pages/admin-login/index",
  ADMIN_DASHBOARD: "/pages/admin-dashboard/index",
  ADMIN_ORDERS: "/pages/admin-orders/index",
  ADMIN_DISHES: "/pages/admin-dishes/index",
  ADMIN_STATS: "/pages/admin-stats/index"
});
